package com.mycompany.lpoo_sistemaestacionamentoifsul.Frame;

import com.mycompany.lpoo_sistemaestacionamentoifsul.dao.PersistenciaJPA;
import com.mycompany.lpoo_sistemaestacionamentoifsul.dao.PessoaRepositorio;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import model.Modelo;
import model.Pessoa;
import model.TipoVeiculo;
import model.Veiculo;
import model.VeiculoOficial;

/**
 *
 * @author ggbra
 */
public class TelaCadastroVeiculo extends javax.swing.JDialog {

    private Veiculo veiculo;
    private VeiculoOficial veiculoOficial;
    private List<Pessoa> pessoasCadastradas;
    private List<Modelo> modelosCadastrados;

    PersistenciaJPA jpa;
    PessoaRepositorio pessoaRepositorio;

    /**
     * Creates new form TelaCadastroPessoa
     */
    public TelaCadastroVeiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jpa = new PersistenciaJPA();
        pessoaRepositorio = new PessoaRepositorio();

        this.popularTipoVeiculo();
        pnlDadosVeiculoOficial.setVisible(false);
        pessoasCadastradas = new ArrayList<>();
        this.popularPessoas();
        modelosCadastrados = new ArrayList<>();
         this.popularModelosCadastrados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloCadastroPessoa = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lblCor = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        jcbOficial = new javax.swing.JCheckBox();
        cmbTipoVeiculo = new javax.swing.JComboBox<>();
        lblTipoVeiculo = new javax.swing.JLabel();
        pnlDadosVeiculoOficial = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtChassi = new javax.swing.JTextField();
        lblRenavan = new javax.swing.JLabel();
        txtDadosVeiculoOficial = new javax.swing.JLabel();
        lblChassi = new javax.swing.JLabel();
        txtRenavan = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbPessoas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbModelo = new javax.swing.JComboBox<>();
        bttnCadastrarModelo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTituloCadastroPessoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloCadastroPessoa.setText("Cadastro de Veiculo");

        lblPlaca.setText("Placa:");

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        lblCor.setText("Cor:");

        txtCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorActionPerformed(evt);
            }
        });

        jcbOficial.setText("Veiculo Oficial");
        jcbOficial.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbOficialItemStateChanged(evt);
            }
        });
        jcbOficial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbOficialActionPerformed(evt);
            }
        });

        lblTipoVeiculo.setText("Tipo Veiculo:");

        txtChassi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChassiActionPerformed(evt);
            }
        });

        lblRenavan.setText("Renavan:");

        txtDadosVeiculoOficial.setText("<html>\n<b>Dados Veículo Oficial</b>\n\n</html>");

        lblChassi.setText("Chassi:");

        txtRenavan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRenavanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDadosVeiculoOficialLayout = new javax.swing.GroupLayout(pnlDadosVeiculoOficial);
        pnlDadosVeiculoOficial.setLayout(pnlDadosVeiculoOficialLayout);
        pnlDadosVeiculoOficialLayout.setHorizontalGroup(
            pnlDadosVeiculoOficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosVeiculoOficialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosVeiculoOficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosVeiculoOficialLayout.createSequentialGroup()
                        .addComponent(lblChassi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(lblRenavan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRenavan, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(pnlDadosVeiculoOficialLayout.createSequentialGroup()
                        .addComponent(txtDadosVeiculoOficial, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosVeiculoOficialLayout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())))
        );
        pnlDadosVeiculoOficialLayout.setVerticalGroup(
            pnlDadosVeiculoOficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosVeiculoOficialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDadosVeiculoOficial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(pnlDadosVeiculoOficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRenavan)
                    .addComponent(lblChassi)
                    .addComponent(txtRenavan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Proprietário:");

        cmbPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPessoasActionPerformed(evt);
            }
        });

        jLabel2.setText("Modelo:");

        cmbModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbModeloActionPerformed(evt);
            }
        });

        bttnCadastrarModelo.setText("+");
        bttnCadastrarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCadastrarModeloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDadosVeiculoOficial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloCadastroPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPlaca)
                                    .addComponent(lblCor)
                                    .addComponent(lblTipoVeiculo))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)
                                        .addComponent(jcbOficial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bttnCadastrarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTituloCadastroPessoa)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCor)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbOficial)
                    .addComponent(cmbTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoVeiculo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bttnCadastrarModelo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(pnlDadosVeiculoOficial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (veiculo == null) {
            veiculo = new Veiculo();
        }

        veiculo.setPlaca(txtPlaca.getText());
        veiculo.setCor(txtCor.getText());
        veiculo.setTipoVeiculo((TipoVeiculo) cmbTipoVeiculo.getModel().getSelectedItem());
        veiculo.setProprietario((Pessoa) cmbPessoas.getModel().getSelectedItem());
        veiculo.setModelo((Modelo) cmbModelo.getModel().getSelectedItem());
        veiculo.setVeiculoOficial(false);

        if (jcbOficial.isSelected()) {
            if (veiculoOficial == null) {
                veiculoOficial = new VeiculoOficial();
                veiculo.setVeiculoOficial(true);
            }

            veiculoOficial.setChassi(txtChassi.getText());
            veiculoOficial.setRenavan(txtRenavan.getText());
        }
        jpa.conexaoAberta();
        try {
            jpa.persist(veiculo);
            if (jcbOficial.isSelected()) {
                jpa.persist(veiculoOficial);
            }
        } catch (Exception ex) {
            Logger.getLogger(TelaVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        jpa.fecharConexao();

        dispose();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jcbOficialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbOficialActionPerformed
        this.habilitarInserirDadosVeiculoOficial();
    }//GEN-LAST:event_jcbOficialActionPerformed

    private void txtChassiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChassiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChassiActionPerformed

    private void txtRenavanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRenavanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRenavanActionPerformed

    private void jcbOficialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbOficialItemStateChanged
        this.habilitarInserirDadosVeiculoOficial();
    }//GEN-LAST:event_jcbOficialItemStateChanged

    private void cmbPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPessoasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPessoasActionPerformed

    private void cmbModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbModeloActionPerformed

    private void bttnCadastrarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCadastrarModeloActionPerformed
        TelaCadastroModelo tlModelo = new TelaCadastroModelo(this, true);
        tlModelo.setVisible(true);
        
        this.popularModelosCadastrados();
    }//GEN-LAST:event_bttnCadastrarModeloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroVeiculo dialog = new TelaCadastroVeiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void habilitarInserirDadosVeiculoOficial() {
        if (jcbOficial.isSelected()) {
            pnlDadosVeiculoOficial.setVisible(true);
        } else {
            pnlDadosVeiculoOficial.setVisible(false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton bttnCadastrarModelo;
    private javax.swing.JComboBox<Modelo> cmbModelo;
    private javax.swing.JComboBox<String> cmbPessoas;
    private javax.swing.JComboBox<TipoVeiculo> cmbTipoVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox jcbOficial;
    private javax.swing.JLabel lblChassi;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblRenavan;
    private javax.swing.JLabel lblTipoVeiculo;
    private javax.swing.JLabel lblTituloCadastroPessoa;
    private javax.swing.JPanel pnlDadosVeiculoOficial;
    private javax.swing.JTextField txtChassi;
    private javax.swing.JTextField txtCor;
    private javax.swing.JLabel txtDadosVeiculoOficial;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtRenavan;
    // End of variables declaration//GEN-END:variables

    public Veiculo getVeiculo() {
        return veiculo;
    }

    public void setVeiculo(Veiculo veiculo) {
        this.veiculo = veiculo;
        txtPlaca.setText(veiculo.getPlaca());
        txtCor.setText(veiculo.getCor());
        jcbOficial.setSelected(veiculo.isVeiculoOficial());
        cmbTipoVeiculo.setSelectedItem(veiculo.getTipoVeiculo());
        cmbPessoas.setSelectedItem(veiculo.getProprietario());
        cmbModelo.setSelectedItem(veiculo.getModelo());
    }

    public VeiculoOficial getVeiculoOficial() {
        return veiculoOficial;
    }

    public void setVeiculoOficial(VeiculoOficial veiculoOficial) {
        this.veiculoOficial = veiculoOficial;
        txtChassi.setText(veiculoOficial.getChassi());
        txtRenavan.setText(veiculoOficial.getRenavan());
    }

    private void popularTipoVeiculo() {
        DefaultComboBoxModel<TipoVeiculo> model = new DefaultComboBoxModel<>();
        model.addElement(null);

        for (TipoVeiculo vinculo : TipoVeiculo.values()) {
            model.addElement(vinculo);
        }
        cmbTipoVeiculo.setModel(model);

        cmbTipoVeiculo.setSelectedItem(null);
    }

    private void popularPessoas() {
        try {
            pessoasCadastradas = pessoaRepositorio.getAll();
            if (pessoasCadastradas == null || pessoasCadastradas.isEmpty()) {
                System.err.println("Nenhuma pessoa encontrada para popular o JComboBox.");
                return;
            }

            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement("Selecione uma pessoa");

            for (Pessoa pessoa : pessoasCadastradas) {
                model.addElement(pessoa.getNome());
            }

            cmbPessoas.setModel(model);
            cmbPessoas.setSelectedItem("Selecione uma pessoa");
        } catch (Exception e) {
            Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private Pessoa getPessoaSelecionada() {
        int selectedIndex = cmbPessoas.getSelectedIndex();
        if (selectedIndex > 0) {
            return pessoasCadastradas.get(selectedIndex - 1);
        }
        return null;
    }

   private void popularModelosCadastrados() {
    try {
        modelosCadastrados = jpa.getModelos();
        
        DefaultComboBoxModel<Modelo> model = new DefaultComboBoxModel<>();
        model.addElement(null);
        for (Modelo modelo : modelosCadastrados) {
            model.addElement(modelo);
           
        }

        cmbModelo.setModel(model);
        cmbModelo.setSelectedItem(null);
    } catch (Exception e) {
        Logger.getLogger(TelaCadastroVeiculo.class.getName()).log(Level.SEVERE, null, e);
    }
}



    public List<Pessoa> getPessoasCadastradas() {
        return pessoasCadastradas;
    }

    public void setPessoasCadastradas(List<Pessoa> pessoasCadastradas) {
        this.pessoasCadastradas = pessoasCadastradas;
    }

    public List<Modelo> getModelosCadastrados() {
        return modelosCadastrados;
    }

    public void setModelosCadastrados(List<Modelo> modelosCadastrados) {
        this.modelosCadastrados = modelosCadastrados;
    }
}
