/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lpoo_sistemaestacionamentoifsul.Frame;

import com.mycompany.lpoo_sistemaestacionamentoifsul.dao.PersistenciaJPA;
import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Veiculo;

/**
 *
 * @author ggbra
 */
public class TelaVeiculo extends javax.swing.JFrame {

    PersistenciaJPA jpa;

    /**
     * Creates new form TelaVeiculo
     */
    public TelaVeiculo() {
        initComponents();
        this.popularComboBox();
        jpa = new PersistenciaJPA();
        this.carregarVeiculosNaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        pnlVinculoPessoa = new javax.swing.JPanel();
        lblBuscaPlaca = new javax.swing.JLabel();
        cmbTipoVeiculo = new javax.swing.JComboBox<>();
        lblBuscaVeiculoOficial = new javax.swing.JLabel();
        txtBuscaPlaca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVeiculo = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setText("Veiculos Cadastrados");

        lblBuscaPlaca.setText("Placa:");

        cmbTipoVeiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoVeiculoItemStateChanged(evt);
            }
        });
        cmbTipoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoVeiculoActionPerformed(evt);
            }
        });

        lblBuscaVeiculoOficial.setText("Veículo Oficial:");

        txtBuscaPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaPlacaActionPerformed(evt);
            }
        });
        txtBuscaPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaPlacaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlVinculoPessoaLayout = new javax.swing.GroupLayout(pnlVinculoPessoa);
        pnlVinculoPessoa.setLayout(pnlVinculoPessoaLayout);
        pnlVinculoPessoaLayout.setHorizontalGroup(
            pnlVinculoPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVinculoPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscaPlaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBuscaVeiculoOficial, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cmbTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlVinculoPessoaLayout.setVerticalGroup(
            pnlVinculoPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVinculoPessoaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlVinculoPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscaPlaca)
                    .addComponent(cmbTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscaVeiculoOficial))
                .addContainerGap())
        );

        tblVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Placa", "Proprietário", "Oficial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVeiculo.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblVeiculo);
        tblVeiculo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnNovo)
                        .addGap(37, 37, 37)
                        .addComponent(btnEditar)
                        .addGap(29, 29, 29)
                        .addComponent(btnRemover))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pnlVinculoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlVinculoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        TelaCadastroVeiculo tlCadastro = new TelaCadastroVeiculo(this, rootPaneCheckingEnabled);
        tlCadastro.setVisible(true);

        this.carregarVeiculosNaTabela();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void cmbTipoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoVeiculoActionPerformed
    
    }//GEN-LAST:event_cmbTipoVeiculoActionPerformed

    private void cmbTipoVeiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoVeiculoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.carregarVeiculosFiltro();
        }
    }//GEN-LAST:event_cmbTipoVeiculoItemStateChanged

    private void txtBuscaPlacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaPlacaKeyReleased
        this.carregarVeiculosFiltro();
    }//GEN-LAST:event_txtBuscaPlacaKeyReleased

    private void txtBuscaPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaPlacaActionPerformed
        
    }//GEN-LAST:event_txtBuscaPlacaActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
 
        List<Veiculo> veiculosCadastrados = jpa.getAll();

        int linhaSelecionada = tblVeiculo.getSelectedRow();

        if (linhaSelecionada != -1) {

            Veiculo veiculoSelecionado = veiculosCadastrados.get(linhaSelecionada);

            int confirmacao = JOptionPane.showConfirmDialog(
                    this,
                    "Tem certeza que deseja excluir o veículo com placa " + veiculoSelecionado.getPlaca() + "?",
                    "Confirmação de Exclusão",
                    JOptionPane.YES_NO_OPTION
            );
            if (confirmacao == JOptionPane.YES_OPTION) {
                try {

                    jpa.conexaoAberta();
                    jpa.remover(veiculoSelecionado);
                    jpa.fecharConexao();

                    DefaultTableModel model = (DefaultTableModel) tblVeiculo.getModel();
                    model.removeRow(linhaSelecionada);
      
                    this.carregarVeiculosNaTabela();
                    JOptionPane.showMessageDialog(this, "Veículo removido com sucesso.");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Erro ao remover veículo: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um veículo para remover.");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       jpa.conexaoAberta();
        List<Veiculo> veiculosCadastrados = jpa.getAll();
        jpa.fecharConexao();
        int linhaSelecionada = tblVeiculo.getSelectedRow();

        if (linhaSelecionada != -1) {

           Veiculo veiculoSelecionado = veiculosCadastrados.get(linhaSelecionada);
        
           TelaCadastroVeiculo telaEdicao = new TelaCadastroVeiculo(this, rootPaneCheckingEnabled);

            telaEdicao.setVeiculo(veiculoSelecionado);
            telaEdicao.setVisible(true);
            
            this.carregarVeiculosNaTabela();
        } else {
            
            JOptionPane.showMessageDialog(this, "Selecione um veículo para editar");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void carregarVeiculosNaTabela() {
        List<Veiculo> veiculosCadastrados = jpa.getAll();

        DefaultTableModel model = (DefaultTableModel) tblVeiculo.getModel();

        model.setRowCount(0);

        for (Veiculo veiculo : veiculosCadastrados) {
            Object[] dadosVeiculo = {
                veiculo.getPlaca(),
                veiculo.getProprietario().getNome(),
                veiculo.isVeiculoOficial() ? "Sim" : "Não"
            };
            model.addRow(dadosVeiculo);
        }

        tblVeiculo.setModel(model);

        this.setSize(600, 400);
        this.setVisible(true);
    }

    private void carregarVeiculosFiltro() {
        jpa.conexaoAberta();

        String placa = txtBuscaPlaca.getText().trim();
        String tipo = (String) cmbTipoVeiculo.getSelectedItem();

        List<Veiculo> veiculosCadastrados = jpa.getVeiculoFiltro(placa, tipo);

        if (veiculosCadastrados == null || ((String) cmbTipoVeiculo.getModel().getSelectedItem() == null && (txtBuscaPlaca.getText() == null || txtBuscaPlaca.getText().isEmpty()))) {
            this.carregarVeiculosNaTabela();
        } else {
            DefaultTableModel model = (DefaultTableModel) tblVeiculo.getModel();

            model.setRowCount(0);

            for (Veiculo veiculo : veiculosCadastrados) {
                Object[] dadosVeiculo = {
                    veiculo.getPlaca(),
                    veiculo.getProprietario().getNome(),
                    veiculo.isVeiculoOficial() ? "Sim" : "Não"
                };
                model.addRow(dadosVeiculo);
            }
            tblVeiculo.repaint();
        }
        jpa.fecharConexao();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVeiculo().setVisible(true);
            }
        });
    }

    private void popularComboBox() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        model.addElement(" ");
        model.addElement("Sim");
        model.addElement("Não");

        cmbTipoVeiculo.setModel(model);
        cmbTipoVeiculo.setSelectedItem(" ");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox<String> cmbTipoVeiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscaPlaca;
    private javax.swing.JLabel lblBuscaVeiculoOficial;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlVinculoPessoa;
    private javax.swing.JTable tblVeiculo;
    private javax.swing.JTextField txtBuscaPlaca;
    // End of variables declaration//GEN-END:variables
}
